version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes: 
      - ./dev_scripts/sql:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local